services:
  # Serviço do backend (Laravel com Sail e SQLite)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Serviço do frontend (Vue 3 com Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    command: yarn dev --host 0.0.0.0 --port 3000

  # Serviço da fila de emails
  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: queue
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    networks:
      - app-network
    command: php artisan queue:work --queue=back_emails

networks:
  app-network:
    driver: bridge
